apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: hello-osc
  namespace: default
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OscCluster
    name: hello-osc
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscCluster
metadata:
  name: hello-osc
  namespace: default
spec:
  network:
    Loadbalancer:
      loadbalancername: OscSdkExample-7
      subregionname: eu-west-2a
    net:
      ipRange: "172.19.95.128/25"
    subnet:
      ipSubnetRange: "172.19.95.192/27"
