name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17.8'
    - name: Lint
      run: make vet
      shell: bash
    - name: unit-test
      run: |
        make unit-test
        cat covers.txt
      shell: bash     
