ame: test

on:
  push:
    branches:    
      - 'test-rke'
  pull_request_target:
    branches: [ test-rke ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/checkout@v3
      with:
        repository: 'outscale-vbr/osc-k8s-rke-cluster'
        path: 'rke-cluster-for-cluster-api'
        ref: add_volume_argument
    - uses: azure/setup-kubectl@v2.0
      with:
        version: v1.22.7
      id: install
    - name: Current cluster
      run: |
        mkdir rke-cluster-for-cluster-api/rke
	echo "$KUBECONFIG" > ./rke-cluster-for-cluster-api/rke/kube_config_cluster.yml
      shell: bash
      env:
        KUBECONFIG: ${{secrets.KUBECONFIG}}
    - name: Wait Kubernetes control plane is up
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 60
        max_attempts: 10
        command: kubectl get --raw='/readyz?verbose'  
      env:
        KUBECONFIG: rke-cluster-for-cluster-api/rke/kube_config_cluster.yml
    - name: Wait all infrastructure app are up and running
      uses: jupyterhub/action-k8s-await-workloads@v1
      with:
        workloads: ""
        namespace: "" 
        timeout: 600
        max-restarts: 0
      env:
        KUBECONFIG: rke-cluster-for-cluster-api/rke/kube_config_cluster.yml
