name: unit-func-e2e-test

on:
  push:
    branches:    
      - 'teststack'
    paths:
      - "**.go"
      - "**.yaml"
      - "!capm.yaml"
      - "!osc-secret.yaml"
      - "!example/**.yaml" 
      - "Makefile"
  pull_request_target:
    branches: [ teststack ]

jobs:
  testenv:
    runs-on: [self-hosted, linux]
    steps:
    - name: Checkout cluster-api-outscale
      uses: actions/checkout@v3
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
    - name: Checkout osc-k8s-rke-cluster
      uses: actions/checkout@v3
      with:
        repository: 'outscale-dev/osc-k8s-rke-cluster'
        path: "rke-cluster-for-cluster-api"
        ref: master
    - name: Deploy Cluster
      uses: ./rke-cluster-for-cluster-api/github_actions/deploy_cluster/
      with:
        repository_folder: "rke-cluster-for-cluster-api"
        rke_version: "v1.3.9"
        osc_access_key: ${{ secrets.OSC_ACCESS_KEY }}
        osc_secret_key: ${{ secrets.OSC_SECRET_KEY }}
        osc_region: ${{ secrets.OSC_REGION }}
        kubernetes_version: "v1.22.7-rancher1-2"
        bastion_vm_type: "tinav5.c4r8p1"
        bastion_volume_type: "io1"
        bastion_volume_size: 30
        bastion_iops: 1500
        control_plane_vm_type: "tinav5.c4r8p1"
        control_plane_count: 1
        control_plane_volume_type: "io1"
        control_plane_volume_size: 30
        control_plane_iops: 1500
        worker_vm_type: "tinav5.c4r8p1"
        worker_count: 2
        worker_volume_type: "io1"
        worker_volume_size: 30
        worker_iops: 1500
        KUBECONFIG: rke-cluster-for-cluster-api/rke/kube_config_cluster.yml
    - name: Destroy cluster
      uses: ./rke-cluster-for-cluster-api/github_actions/destroy_cluster/
      if: ${{ always() }}
      with:
        repository_folder: "rke-cluster-for-cluster-api"
        osc_access_key: ${{ secrets.OSC_ACCESS_KEY }}
        osc_secret_key: ${{ secrets.OSC_SECRET_KEY }}
        osc_region: ${{ secrets.OSC_REGION }}
